erDiagram

   JOB {
       int id

       int primary_post_id
       text comments

       datetime created
       datetime modified
   }

   STAGE {
       int id
       int sort_order
       string name
       string color
   }

   JOB_STAGE {
       int id
       int stage_id
       int job_id
       datetime timestamp
       text comment
       string url
   }

   POST {
       int id

       int job_id
       int connection_id
       string unique_id

       string url
       string company
       string title
       string description
       string location

       datetime created
       datetime modified
   }

   CONNECTOR {
       string name
       string version
       string description
       json config_schema
       json query_schema
   }

   CONNECTION {
       int id
       string connector_name
       string name
       json config
   }

   SCHEDULE {
       int id
       int connection_id
       bool enabled
       interval query_interval
       json query
   }

   QUERY {
       int id
       int schedule_id
       int connection_id
       datetime created
       datetime started
       datetime ended
       string error_message
       json query
   }

   QUERY_RESULT {
       int id
       int query_id
       int post_id
   }

   QUERY_LOG {
       int id
       int query_id
       datetime timestamp
       text message
   }

   STAGE ||--|{ JOB_STAGE : ""
   JOB ||--o{ JOB_STAGE : ""
   JOB ||--|{ POST : ""
   CONNECTOR ||--o{ CONNECTION  : ""
   CONNECTION o|--o{ POST : ""
   CONNECTION ||--o{ QUERY : ""
   CONNECTION ||--o{ SCHEDULE : ""
   SCHEDULE o|--O{ QUERY : ""
   POST ||--o{ QUERY_RESULT : ""
   QUERY ||--o{ QUERY_RESULT : ""
   QUERY ||--o{ QUERY_LOG : ""


